### ISSUE TITLE
DMG damaged

### ISSUE THREAD

**Issue by N214** [cebby2420/via-desktop#5]
Apple ARM edition DMG dammaged, cannot open, version [v2024.11.5](https://github.com/cebby2420/via-desktop/releases/tag/v2024.11.5).

**Comment by se-bastiaan** [comment]
Have you read the Readme?

**Comment by cebby2420** [comment]
Have you read the Readme?
________________________________
From: N214 ***@***.***>
Sent: Saturday, November 9, 2024 7:46:51 PM
To: cebby2420/via-desktop ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [cebby2420/via-desktop] DMG damaged (Issue #5)


Apple ARM edition DMG dammaged, cannot open, version v2024.11.5<https://github.com/cebby2420/via-desktop/releases/tag/v2024.11.5>.

**Comment by N214** [comment]
Not referring to that error, the previous version is working fine.

**Comment by cebby2420** [comment]
I don't entirely understand the error you are getting then. Without some more information I cannot help you. Do you maybe have a screenshot? macOS log files?

Have you tried running the xattr command on the .app? What are the results of that?

**Comment by N214** [comment]
I have the pop-up below, running the `xattr -d com.apple.quarantine path of my app file` does solve the issue but I did not do that for the previous release, something changed in this one. 

<img width="264" alt="image" src="https://github.com/user-attachments/assets/258b2ab0-9f00-4716-a10e-7be123a7cd7b">

**Comment by cebby2420** [comment]
If you downloaded the x64 instead of the arm64 release then the error was probably not present on the previous version indeed. That first one opens just fine for some reason. 

The error is to be expected however, since the build is unsigned.

**Comment by smiba** [comment]
Same issue for me on my arm64 MacBook Pro M3, app is seen as damaged and does not open.

@cebby2420

**Comment by cebby2420** [comment]
@smiba Did you try the xattr command?

**Comment by smiba** [comment]
I'm very sorry, I missed the notice in the readme and was expecting (as the message was not the typical quarantine message) that the solution earlier in this issue was irrelevant to me.

Removing the com.apple.quarantine attribute did fix the ARM64 build for me, incredibly confusing error from Apple's side. Sorry for bothering you!
