### ISSUE TITLE
Via-desktop 2024.12.16 doesn't save any settings

### ISSUE THREAD

**Issue by JeroenTuinstra** [cebby2420/via-desktop#9]
The new desktop app doesn't safe any settings. 
When you enable under settings "Show Design Tab", when you close the app and open it again you have to enable it again. 
Each time you have to confirm that this feature is for development purposes. 
When you upload your own JSON definitions file, it also doesn't remember it. You re-open the app and you have to enable the design tab, confirm the warning and upload your JSON file again.
And then it doesn't recognize your keyboard (NuPhy 96 V2, firmware 2.1). The online app in edge works, but the offline desktop app not.

**Comment by JeroenTuinstra** [comment]
It does connect now to the keyboard. But settings are not remembered/stored. You have to do all steps each time.

**Comment by cebby2420** [comment]
see #1
